### ISSUE TITLE
Plugin init code & SEOmatic

### ISSUE THREAD

**Issue by khalwat** [mmikkel/CpClearCache-Craft#1]
I had someone report an issue where SEOmatic refused to work properly: https://github.com/nystudio107/craft-seomatic/issues/41

We narrowed it down to the CP Clear Cache plugin; if it wasn't installed, everything worked fine. Here's what I think is going on:

https://github.com/mmikkel/CpClearCache-Craft/blob/master/src/CpClearCache.php#L83

I'd suggest waiting to install your event handlers until after all plugins have loaded, ala:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L307

Also in your `View::EVENT_BEFORE_RENDER_TEMPLATE` event handler, you might want to check:

```
Craft::$app->getView()->getIsRenderingPageTemplate()
```
...before adding your Asset Bundle, as there's no sense in adding it if an object or string template is rendering (and it'd add overhead to what should be pretty performant calls).

**Comment by mmikkel** [comment]
Hey @khalwat – thanks a lot for basically doing all the work for me :) I'll get this sorted ASAP.

**Comment by khalwat** [comment]
I took a look at the Craft CMS View code, and it looks like it doesn't fire the `View::EVENT_BEFORE_RENDER_TEMPLATE` event when rendering a string or object template, so you can ignore that part. Sorry about that! :)

**Comment by mmikkel** [comment]
Fixed in [CP Clear Cache 1.0.1](https://github.com/mmikkel/CpClearCache-Craft/releases/tag/1.0.1).
