### ISSUE TITLE
Does not play well aynmore wit CP Nav

### ISSUE THREAD

**Issue by wmdhosting** [mmikkel/CpClearCache-Craft#10]
Hey :)

on Craft 4  all last versions

Does not play well with CP Nav
i get this..  instead of popup.. .  when i turn off CP Nav it works OK. 

![Snag_1b114c6](https://user-images.githubusercontent.com/76176291/201079085-0449d782-1329-40d5-8cf0-5804fc7f7cb0.png)

**Comment by mmikkel** [comment]
Seems that CP Nav changes the ID attribute for CP Clear Cache's nav item, which messed up the JavaScript click handler. 

Found a workaround; should be fixed in CP Clear Cache [v. 1.3.0](https://github.com/mmikkel/CpClearCache-Craft/releases/tag/1.3.0)!
