### ISSUE TITLE
Cp Clear Cache enables Twig and stop some plugins being enabled

### ISSUE THREAD

**Issue by zizther** [mmikkel/CpClearCache-Craft#4]
I tried installing another plugin while having CP Clear Cache enabled.
However I was unable to install this plugin (Agent) due to an error I was getting.

`Unable to add global "agent" as the runtime or the extensions have already been initialized.`

This was due to CP Clear Cache initializing Twig already. Is there a way to get around this, so other plugins don't encounter this issue?

**Comment by mmikkel** [comment]
Hi @zizther – thanks for reporting! 

I'll do some digging ASAP; is [this](https://plugins.craftcms.com/agent) the plugin you're seeing the issue with?

**Comment by zizther** [comment]
Thanks man.
That is the correct plugin.

**Comment by mmikkel** [comment]
Hi @zizther – just published [CP Clear Cache v. 1.0.4](https://github.com/mmikkel/CpClearCache-Craft/releases/tag/1.0.4), which should resolve this issue.

**Comment by zizther** [comment]
Superb job.
Thanks for the quick fix
